"use client";

import { ChangeEvent, FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Activity, Bot, BrainCircuit, FileText, Gauge, LayoutDashboard, LogOut, Mail, Menu, MessageSquareText, RefreshCw, Search, Settings, Sparkles, UploadCloud, UserPlus, Users, WandSparkles, X } from "lucide-react";

import { api, formatBytes } from "@/lib/api";
import { Button, Card, EmptyState, Spinner } from "@/components/ui";

type Section = "overview"|"assistant"|"documents"|"team"|"automations"|"market"|"settings";
type User = { id:string; nome:string; email:string; perfil:"admin"|"gestor"|"usuario"; ativo:boolean; empresa_id:string };
type Summary = { empresas:number; usuarios:number; documentos:number; documentos_indexados:number; convites_pendentes:number };
type DocumentRecord = { id:string; nome_original:string; tipo_mime:string; tamanho_bytes:number; status:string; criado_em:string };
type Source = { documento_id:string; nome:string; trecho:string; relevancia:number };
type AssistantAnswer = { resposta:string; fontes:Source[]; modo:string };
type Invite = { id:string; email:string; perfil:string; status:string; expira_em:string };

const nav = [
  ["overview","Visão geral",LayoutDashboard],["assistant","Assistente",Bot],["documents","Documentos",FileText],
  ["team","Equipe",Users],["automations","Automações",WandSparkles],["market","Mercado",Activity],["settings","Configurações",Settings],
] as const;

export function Workspace(){
  const router=useRouter(); const[section,setSection]=useState<Section>("overview"); const[mobile,setMobile]=useState(false);
  const[user,setUser]=useState<User|null>(null); const[summary,setSummary]=useState<Summary|null>(null); const[docs,setDocs]=useState<DocumentRecord[]>([]); const[members,setMembers]=useState<User[]>([]); const[invites,setInvites]=useState<Invite[]>([]);
  const[loading,setLoading]=useState(true); const[error,setError]=useState(""); const[toast,setToast]=useState("");
  const notify=useCallback((message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),3500)},[]);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const me=await api<User>("/auth/me");setUser(me);const [s,d,m]=await Promise.all([api<Summary>("/dashboard/resumo"),api<DocumentRecord[]>("/documentos/"),api<User[]>("/usuarios/")]);setSummary(s);setDocs(d);setMembers(m);if(me.perfil!=="usuario")setInvites(await api<Invite[]>("/convites/"));}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar dados.");}finally{setLoading(false)}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.replace("/login");router.refresh()}
  const title=nav.find(([id])=>id===section)?.[1]??"Núcleo";
  return <div className="workspace"><aside className={mobile?"sidebar open":"sidebar"}><div className="sidebar-head"><span className="brand"><i><BrainCircuit size={20}/></i>Núcleo AI</span><button className="icon-button mobile-only" onClick={()=>setMobile(false)} aria-label="Fechar menu"><X/></button></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={section===id?"active":""} onClick={()=>{setSection(id);setMobile(false)}}><Icon size={18}/>{label}{id==="documents"&&docs.length>0?<span>{docs.length}</span>:null}</button>)}</nav><div className="sidebar-user"><span>{user?.nome.slice(0,2).toUpperCase()??"NU"}</span><div><b>{user?.nome??"Carregando"}</b><small>{user?.perfil??""}</small></div><button onClick={logout} aria-label="Sair"><LogOut size={17}/></button></div></aside>{mobile&&<button className="mobile-backdrop" onClick={()=>setMobile(false)} aria-label="Fechar menu"/>}<main className="workspace-main"><header className="topbar"><button className="icon-button mobile-only" onClick={()=>setMobile(true)} aria-label="Abrir menu"><Menu/></button><div><p className="eyebrow">WORKSPACE EMPRESARIAL</p><h1>{title}</h1></div><Button className="ghost" onClick={()=>void load()}><RefreshCw size={15}/>Atualizar</Button></header><div className="content">{loading?<Loading/>:error?<ErrorState message={error} retry={load}/>:<SectionContent section={section} user={user!} summary={summary!} docs={docs} setDocs={setDocs} members={members} invites={invites} setInvites={setInvites} notify={notify}/>}</div></main>{toast&&<div className="toast" role="status"><Sparkles size={17}/>{toast}</div>}</div>
}

function Loading(){return <div className="loading-grid">{[1,2,3,4].map(i=><div className="skeleton" key={i}/>)}</div>}
function ErrorState({message,retry}:{message:string;retry:()=>Promise<void>}){return <EmptyState icon={Gauge} title="Não foi possível carregar o workspace" description={message} action={<Button onClick={()=>void retry()}>Tentar novamente</Button>}/>}

function SectionContent(props:{section:Section;user:User;summary:Summary;docs:DocumentRecord[];setDocs:(d:DocumentRecord[])=>void;members:User[];invites:Invite[];setInvites:(i:Invite[])=>void;notify:(m:string)=>void}){
  if(props.section==="overview")return <Overview {...props}/>; if(props.section==="assistant")return <Assistant/>; if(props.section==="documents")return <Documents {...props}/>; if(props.section==="team")return <Team {...props}/>; if(props.section==="automations")return <Automations/>; if(props.section==="market")return <Market/>; return <SettingsPage user={props.user}/>;
}

function Overview({summary,docs,members}:{summary:Summary;docs:DocumentRecord[];members:User[]}){const metrics=[["Pessoas ativas",summary.usuarios,Users],["Documentos",summary.documentos,FileText],["Fontes indexadas",summary.documentos_indexados,BrainCircuit],["Convites pendentes",summary.convites_pendentes,Mail]] as const;return <><section className="hero-card"><div><p className="eyebrow">OPERAÇÃO CONECTADA</p><h2>Transforme conhecimento em decisões comerciais melhores.</h2><p>Acompanhe a saúde do workspace, consulte fontes internas e automatize tarefas sem perder rastreabilidade.</p></div><span><Sparkles size={38}/></span></section><div className="metric-grid">{metrics.map(([label,value,Icon])=><Card key={label} className="metric"><span><Icon size={19}/></span><div><small>{label}</small><strong>{value}</strong></div></Card>)}</div><div className="split-grid"><Card><div className="card-head"><div><p className="eyebrow">CONHECIMENTO</p><h3>Documentos recentes</h3></div><FileText/></div>{docs.slice(0,4).map(doc=><div className="compact-row" key={doc.id}><span className="file-icon"><FileText size={16}/></span><div><b>{doc.nome_original}</b><small>{formatBytes(doc.tamanho_bytes)}</small></div><em className={`status ${doc.status}`}>{doc.status}</em></div>)}{!docs.length&&<p className="muted">Envie o primeiro documento para alimentar a IA.</p>}</Card><Card><div className="card-head"><div><p className="eyebrow">EQUIPE</p><h3>Acesso ao workspace</h3></div><Users/></div>{members.slice(0,4).map(member=><div className="compact-row" key={member.id}><span className="avatar">{member.nome.slice(0,2).toUpperCase()}</span><div><b>{member.nome}</b><small>{member.email}</small></div><em className="role">{member.perfil}</em></div>)}</Card></div></>}

function Assistant(){const[q,setQ]=useState("");const[answer,setAnswer]=useState<AssistantAnswer|null>(null);const[loading,setLoading]=useState(false);async function ask(e:FormEvent){e.preventDefault();if(q.trim().length<3)return;setLoading(true);try{setAnswer(await api<AssistantAnswer>("/assistente/perguntar",{method:"POST",body:JSON.stringify({pergunta:q})}))}finally{setLoading(false)}}return <div className="assistant-layout"><Card className="assistant-intro"><span><Bot size={26}/></span><div><p className="eyebrow">ASSISTENTE COM FONTES</p><h2>Pergunte aos documentos da sua empresa</h2><p>A resposta indica exatamente quais fontes internas sustentam cada conclusão.</p></div></Card><Card className="chat-card"><div className="chat-body">{answer?<><div className="answer"><span><BrainCircuit size={18}/></span><p>{answer.resposta}</p></div><div className="sources"><p className="eyebrow">FONTES UTILIZADAS</p>{answer.fontes.map(source=><article key={source.documento_id}><FileText size={16}/><div><b>{source.nome}</b><p>{source.trecho}</p></div><em>{Math.round(source.relevancia*100)}%</em></article>)}</div></>:<EmptyState icon={MessageSquareText} title="Comece uma conversa" description="Pergunte sobre processos, propostas, políticas ou qualquer conteúdo já enviado."/>}</div><form className="composer" onSubmit={ask}><textarea value={q} onChange={e=>setQ(e.target.value)} placeholder="Ex.: Como devemos responder a uma objeção de preço?" maxLength={8000}/><Button className="primary" disabled={loading||q.trim().length<3}>{loading?<Spinner/>:<Sparkles size={16}/>}Perguntar</Button></form></Card></div>}

function Documents({docs,setDocs,notify}:{docs:DocumentRecord[];setDocs:(d:DocumentRecord[])=>void;notify:(m:string)=>void}){const[uploading,setUploading]=useState(false);async function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setUploading(true);try{const form=new FormData();form.append("arquivo",file);const saved=await api<DocumentRecord>("/documentos/upload",{method:"POST",body:form});setDocs([saved,...docs]);notify("Documento enviado e processado.")}catch(error){notify(error instanceof Error?error.message:"Falha no envio.")}finally{setUploading(false);e.target.value=""}}return <Card><div className="card-head"><div><p className="eyebrow">BASE DE CONHECIMENTO</p><h2>Documentos</h2><p className="muted">PDF, Word, Excel, texto, CSV e imagens. Limite de 50 MB.</p></div><label className="button primary upload-button">{uploading?<Spinner/>:<UploadCloud size={16}/>}Enviar documento<input type="file" onChange={upload} accept=".pdf,.docx,.xlsx,.xlsm,.txt,.md,.csv,.png,.jpg,.jpeg"/></label></div>{docs.length?<div className="data-table"><div className="table-row table-head"><span>Arquivo</span><span>Formato</span><span>Tamanho</span><span>Status</span></div>{docs.map(doc=><div className="table-row" key={doc.id}><span><FileText size={16}/><b>{doc.nome_original}</b></span><span>{doc.tipo_mime.split("/").pop()}</span><span>{formatBytes(doc.tamanho_bytes)}</span><span><em className={`status ${doc.status}`}>{doc.status}</em></span></div>)}</div>:<EmptyState icon={UploadCloud} title="Sua base ainda está vazia" description="Envie documentos para habilitar respostas empresariais com fontes."/>}</Card>}

function Team({user,members,invites,setInvites,notify}:{user:User;members:User[];invites:Invite[];setInvites:(i:Invite[])=>void;notify:(m:string)=>void}){const[email,setEmail]=useState("");const[perfil,setPerfil]=useState("usuario");const canInvite=user.perfil!=="usuario";async function invite(e:FormEvent){e.preventDefault();try{const item=await api<Invite>("/convites/",{method:"POST",body:JSON.stringify({email,perfil})});setInvites([item,...invites]);setEmail("");notify("Convite enviado com segurança.")}catch(error){notify(error instanceof Error?error.message:"Falha ao convidar.")}}return <div className="split-grid team-grid"><Card><div className="card-head"><div><p className="eyebrow">PESSOAS</p><h2>{members.length} membros</h2></div><Users/></div>{members.map(member=><div className="compact-row" key={member.id}><span className="avatar">{member.nome.slice(0,2).toUpperCase()}</span><div><b>{member.nome}</b><small>{member.email}</small></div><em className="role">{member.perfil}</em></div>)}</Card><Card><div className="card-head"><div><p className="eyebrow">CONVITES</p><h2>Adicionar pessoa</h2></div><UserPlus/></div>{canInvite?<form className="form-stack" onSubmit={invite}><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="pessoa@empresa.com" required/></label><label>Perfil<select value={perfil} onChange={e=>setPerfil(e.target.value)}><option value="usuario">Usuário</option><option value="gestor">Gestor</option><option value="admin">Administrador</option></select></label><Button className="primary"><Mail size={16}/>Enviar convite</Button></form>:<p className="muted">Apenas gestores e administradores podem enviar convites.</p>}<div className="invite-list">{invites.slice(0,5).map(item=><div key={item.id}><span><b>{item.email}</b><small>Expira em {new Date(item.expira_em).toLocaleDateString("pt-BR")}</small></span><em className="status">{item.status}</em></div>)}</div></Card></div>}

function Automations(){const[type,setType]=useState("email");const[context,setContext]=useState("");const[result,setResult]=useState("");const[loading,setLoading]=useState(false);async function generate(e:FormEvent){e.preventDefault();setLoading(true);try{const data=await api<{conteudo:string}>("/automacoes/gerar",{method:"POST",body:JSON.stringify({tipo:type,contexto:context})});setResult(data.conteudo)}finally{setLoading(false)}}return <div className="split-grid"><Card><p className="eyebrow">GERADOR EMPRESARIAL</p><h2>Automatize com contexto real</h2><form className="form-stack" onSubmit={generate}><label>Tipo<select value={type} onChange={e=>setType(e.target.value)}><option value="email">E-mail comercial</option><option value="followup">Follow-up</option><option value="proposta">Proposta</option></select></label><label>Contexto<textarea value={context} onChange={e=>setContext(e.target.value)} minLength={3} placeholder="Descreva cliente, objetivo e próximo passo..." required/></label><Button className="primary" disabled={loading}>{loading?<Spinner/>:<WandSparkles size={16}/>}Gerar conteúdo</Button></form></Card><Card className="result-card"><p className="eyebrow">RESULTADO</p>{result?<div className="generated-text">{result}</div>:<EmptyState icon={Sparkles} title="Pronto para criar" description="O conteúdo será produzido usando apenas as fontes da sua empresa."/>}</Card></div>}

function Market(){const[indicator,setIndicator]=useState("selic");const[data,setData]=useState<{nome:string;fonte:string;pontos:{data:string;valor:number}[]} | null>(null);const[loading,setLoading]=useState(false);async function search(){setLoading(true);try{setData(await api(`/mercado/indicadores/${indicator}?limite=12`))}finally{setLoading(false)}}return <Card><div className="card-head"><div><p className="eyebrow">DADOS OFICIAIS</p><h2>Indicadores de mercado</h2><p className="muted">Séries consultadas diretamente no Banco Central.</p></div><Activity/></div><div className="market-controls"><select value={indicator} onChange={e=>setIndicator(e.target.value)}><option value="selic">Taxa Selic</option><option value="ipca">IPCA</option><option value="cambio">Câmbio USD/BRL</option></select><Button className="primary" onClick={search}>{loading?<Spinner/>:<Search size={16}/>}Consultar</Button></div>{data&&<div className="market-result"><h3>{data.nome}</h3><small>{data.fonte}</small><div className="bar-chart">{data.pontos.map((point,index)=>{const max=Math.max(...data.pontos.map(p=>p.valor),1);return <div key={`${point.data}-${index}`} title={`${point.data}: ${point.valor}`}><i style={{height:`${Math.max(8,(point.valor/max)*100)}%`}}/><span>{point.valor}</span></div>})}</div></div>}</Card>}

function SettingsPage({user}:{user:User}){return <div className="split-grid"><Card><p className="eyebrow">PERFIL</p><h2>Conta autenticada</h2><div className="profile-card"><span className="avatar large">{user.nome.slice(0,2).toUpperCase()}</span><div><h3>{user.nome}</h3><p>{user.email}</p><em className="role">{user.perfil}</em></div></div></Card><Card><p className="eyebrow">SEGURANÇA</p><h2>Arquitetura protegida</h2><ul className="security-list"><li><span>JWT em cookie HttpOnly</span><b>Ativo</b></li><li><span>Isolamento multiempresa</span><b>Ativo</b></li><li><span>Senhas com Argon2</span><b>Ativo</b></li><li><span>Limite de requisições</span><b>Ativo</b></li></ul></Card></div>}
